const homeContent = [
    {
      id: 1,
      pretitle: 'Design',
      title: 'Perfect Fit',
      img1:  `../assets/1.png`,
      img2: "../assets/2.png",
      img3:"../assets/3.png",
      desc: `Innovation isn't always obvious to the eye, but look a little closer at Apple Plug. You'll find it is designed to fit seamlessly into the outdated headphone connector, transforming last year's phone into a modern masterpiece as beautifully as you'd expect from Apple. Once in place, Apple Plug cannot be removed. But why would you want to? Would you want to downgrade? We didn't think so.`,
    },
    {
        id: 2,
        pretitle: 'Innovation',
        title: 'Pure Invention',
        img1:  "../assets/4.png",
        desc: `Innovation questions everything you know. We removed the floppy drive, and people said we were wrong. We weren't. We removed the CD drive, and again people said we were wrong. We weren't. We never are. Apple Plug isn't just a pristine product. It's an essential part of showing others who you are.`,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: './images/item-3.jpeg',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: './images/item-4.jpeg',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: './images/item-5.jpeg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: './images/item-6.jpeg',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: './images/item-7.jpeg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: './images/item-8.jpeg',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: './images/item-9.jpeg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default homeContent;
  